/* Wi-Fi Vault: no modules, works on GitHub Pages and Android. */
(function(){'use strict';
const STORE='kdbx_binary_store',CFG='wifi_vault_github_cfg',SHA='kdbx_github_sha';let db=null,items=[],filter='all',editId=null,stream=null,timer=null;
const $=id=>document.getElementById(id), hidden=(el,value)=>el&&el.classList.toggle('hidden',value), val=x=>x==null?'':typeof x.getText==='function'?x.getText():String(x), err=e=>e&&e.message||String(e||'Unknown error');
function b64(buf){let a=new Uint8Array(buf),s='';for(let i=0;i<a.length;i+=32768)s+=String.fromCharCode.apply(null,a.subarray(i,i+32768));return btoa(s)}function bin(s){s=atob(String(s).replace(/\s/g,''));let a=new Uint8Array(s.length);for(let i=0;i<s.length;i++)a[i]=s.charCodeAt(i);return a.buffer}function esc(s){return val(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function creds(p){return new kdbxweb.Credentials(kdbxweb.ProtectedValue.fromString(p))}async function saveDb(){if(db)localStorage.setItem(STORE,b64(await db.save()))}function localDb(){let x=localStorage.getItem(STORE);return x?bin(x):null}
async function create(p){let aes=kdbxweb.Consts.KdfId.Aes;db=kdbxweb.Kdbx.create(creds(p),'Wi-Fi Vault');if(db.header.setKdf)db.header.setKdf(aes);else db.header.kdfParameters.set('$kdf',aes);await saveDb()}async function unlock(buf,p){db=await kdbxweb.Kdbx.load(buf,creds(p))}
function eid(e){return e.uuid&&(e.uuid.id||e.uuid.toString())}function read(){if(!db)return[];let g=db.getDefaultGroup();return(g?g.allEntries():[]).map(e=>({id:eid(e),ssid:val(e.fields.get('Title')),password:val(e.fields.get('Password')),type:val(e.fields.get('SecurityType'))||'WPA2',favorite:val(e.fields.get('IsFavorite'))==='true'}))}
async function write(r){let g=db.getDefaultGroup(),e=g.allEntries().find(x=>eid(x)===r.id);if(!e)e=db.createEntry(g);e.fields.set('Title',r.ssid);e.fields.set('UserName',r.ssid);e.fields.set('Password',kdbxweb.ProtectedValue.fromString(r.password));e.fields.set('SecurityType',r.type);e.fields.set('IsFavorite',r.favorite?'true':'false');await saveDb()}async function remove(id){let g=db.getDefaultGroup(),e=g.allEntries().find(x=>eid(x)===id);if(e){db.remove(e);await saveDb()}}
function config(){try{let c=JSON.parse(localStorage.getItem(CFG)||'null');if(!c)return null;return{token:String(c.token||'').trim().replace(/^(Bearer|token)\s+/i,''),owner:String(c.owner||'').trim().replace(/^https?:\/\/github\.com\//i,'').split('/')[0],repo:String(c.repo||'').trim().replace(/^https?:\/\/github\.com\//i,'').replace(/^\/+|\/+$/g,'').split('/')[0],file:String(c.file||'vault.kdbx').trim().replace(/^\/+|\/+$/g,'').split('?')[0]}}catch(_){return null}}
function headers(t){return{Authorization:(t.indexOf('ghp_')===0?'token ':'Bearer ')+t,Accept:'application/vnd.github+json','Content-Type':'application/json'}}function api(c){return'https://api.github.com/repos/'+encodeURIComponent(c.owner)+'/'+encodeURIComponent(c.repo)+'/contents/'+c.file.split('/').map(encodeURIComponent).join('/')}
async function apiError(r,what){let j=await r.json().catch(()=>({}));throw new Error(what+' failed (HTTP '+r.status+'): '+(j.message||r.statusText||'Unknown error'))}
async function download(){let c=config();if(!c||!c.token||!c.owner||!c.repo)throw Error('Open Sync settings and enter the private vault repository.');let r;try{r=await fetch(api(c),{headers:headers(c.token)})}catch(e){throw Error('Cannot reach GitHub: '+err(e))}if(r.status===404)throw Error('Vault repository/file not found. Check the exact private repository name and PAT access.');if(!r.ok)await apiError(r,'Download');let j=await r.json();if(!j.content)throw Error('GitHub returned no vault content.');sessionStorage.setItem(SHA,j.sha);return bin(j.content)}
async function upload(){let c=config();if(!c||!c.token||!c.owner||!c.repo)throw Error('Open Sync settings and enter the private vault repository.');let u=api(c),r=await fetch(u,{headers:headers(c.token)});let sha=null;if(r.ok)sha=(await r.json()).sha;else if(r.status!==404)await apiError(r,'Repository lookup');let body={message:'Update encrypted Wi-Fi vault',content:b64(await db.save())};if(sha)body.sha=sha;let p=await fetch(u,{method:'PUT',headers:headers(c.token),body:JSON.stringify(body)});if(p.status===409){r=await fetch(u,{headers:headers(c.token)});if(!r.ok)await apiError(r,'Conflict recovery');body.sha=(await r.json()).sha;p=await fetch(u,{method:'PUT',headers:headers(c.token),body:JSON.stringify(body)})}if(!p.ok)await apiError(p,'Upload');let j=await p.json();if(j.content)sessionStorage.setItem(SHA,j.content.sha)}
function parse(raw){let s=val(raw).trim(),m=s.match(/<SSID\s*>([\s\S]*?)<\/SSID\s*>/i),p=s.match(/<PWD\s*>([\s\S]*?)<\/PWD\s*>/i);if(m||p)return{ssid:m?m[1].trim():'',password:p?p[1].trim():'',type:'WPA2'};if(!/^WIFI:/i.test(s))return null;let f={},key='',v='';for(let i=5;i<s.length;i++){let c=s[i];if(c==='\\'&&i+1<s.length){v+=s[++i];continue}if(c===':'){key=v;v='';continue}if(c===';'){if(key)f[key]=v;key='';v='';continue}v+=c}return{ssid:f.S||'',password:f.P||'',type:f.T||'WPA2'}}
function render(){let q=($('vault-search').value||'').toLowerCase(),list=$('wifi-list');list.innerHTML='';let rows=items.filter(x=>(filter==='all'||x.favorite)&&((x.ssid||'').toLowerCase().includes(q)));hidden($('vault-empty'),rows.length>0);rows.forEach(r=>{let c=document.createElement('div');c.className='wifi-card';c.innerHTML='<div class="card-top"><div><div class="card-ssid">'+esc(r.ssid)+'</div><div class="card-meta">'+esc(r.type)+'</div></div><button class="btn-fav '+(r.favorite?'active':'')+'" type="button">★</button></div><div class="password-display"><span class="pass-text masked-pass">••••••••</span><button class="btn-card show" type="button">Show</button></div><div class="card-actions"><button class="btn-card edit" type="button">Edit</button><button class="btn-card danger del" type="button">Delete</button></div>';c.querySelector('.show').onclick=function(){let x=c.querySelector('.pass-text'),show=x.dataset.show==='1';x.textContent=show?'••••••••':r.password;x.dataset.show=show?'0':'1';this.textContent=show?'Show':'Hide'};c.querySelector('.btn-fav').onclick=async()=>{r.favorite=!r.favorite;await write(r);refresh()};c.querySelector('.edit').onclick=()=>openForm(r);c.querySelector('.del').onclick=async()=>{if(confirm('Delete '+r.ssid+'?')){await remove(r.id);refresh()}};list.appendChild(c)})}function refresh(){items=read();render();$('vault-status-indicator').textContent=db?'Unlocked':'Locked';$('vault-status-indicator').className='status-badge '+(db?'unlocked':'locked')}
function openSettings(){let c=config();if(c){ $('gh-token').value=c.token;$('gh-owner').value=c.owner;$('gh-repo').value=c.repo;$('gh-filename').value=c.file}hidden($('settings-modal'),false)}function openForm(r){editId=r?r.id:null;$('input-ssid').value=r?r.ssid:'';$('input-password').value=r?r.password:'';$('input-auth-type').value=r?r.type:'WPA2';hidden($('confirm-modal'),false)}
async function getVault(){try{let b=await download();localStorage.setItem(STORE,b64(b));alert('Vault downloaded. Enter the original master password to unlock.')}catch(e){alert('Download failed: '+err(e))}}
window.handleUnlockVault=async function(){let p=$('master-password-input').value;if(!p)return alert('Enter your master password.');try{await unlock(localDb(),p);hidden($('auth-modal'),true);refresh()}catch(e){alert('Unlock failed: '+err(e))}};window.handleCreateVault=async function(){let p=$('master-password-input').value;if(p.length<6)return alert('Use at least 6 characters.');try{await create(p);hidden($('auth-modal'),true);refresh()}catch(e){alert('Create failed: '+err(e))}};
document.addEventListener('DOMContentLoaded',function(){if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});$('btn-unlock-vault').onclick=window.handleUnlockVault;$('btn-create-new-kdbx').onclick=window.handleCreateVault;$('btn-download-vault').onclick=getVault;$('btn-auth-settings').onclick=openSettings;$('btn-open-settings').onclick=openSettings;$('btn-close-settings').onclick=()=>hidden($('settings-modal'),true);$('btn-save-settings').onclick=function(){let t=$('gh-token').value.trim(),o=$('gh-owner').value.trim(),r=$('gh-repo').value.trim(),f=$('gh-filename').value.trim()||'vault.kdbx';if(!t||!o||!r)return alert('Token, owner and repository are required.');localStorage.setItem(CFG,JSON.stringify({token:t,owner:o,repo:r,file:f}));hidden($('settings-modal'),true);alert('Settings saved.')};$('btn-sync-cloud').onclick=async function(){let b=this;try{b.disabled=true;b.textContent='⏳ Syncing…';if(db){await upload();alert('Encrypted vault uploaded.')}else await getVault()}catch(e){alert('Sync failed: '+err(e))}finally{b.disabled=false;b.textContent='🔄 Sync'}};$('btn-lock-vault').onclick=()=>{db=null;items=[];refresh();hidden($('auth-modal'),false)};$('btn-export-kdbx').onclick=async()=>{if(!db)return alert('Unlock the vault first.');let u=URL.createObjectURL(new Blob([await db.save()],{type:'application/x-keepass2'})),a=document.createElement('a');a.href=u;a.download='vault.kdbx';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};$('btn-manual-add').onclick=()=>db?openForm():hidden($('auth-modal'),false);$('btn-cancel-save').onclick=()=>hidden($('confirm-modal'),true);$('btn-confirm-save').onclick=async()=>{let s=$('input-ssid').value.trim();if(!s)return alert('SSID is required.');let old=items.find(x=>x.id===editId);await write({id:editId||crypto.randomUUID(),ssid:s,password:$('input-password').value,type:$('input-auth-type').value,favorite:old?old.favorite:false});hidden($('confirm-modal'),true);refresh()};$('vault-search').oninput=render;$('filter-all').onclick=()=>{filter='all';render()};$('filter-favorites').onclick=()=>{filter='favorites';render()};$('file-import-kdbx').onchange=e=>{let f=e.target.files[0],p=$('master-password-input').value;if(!f||!p)return alert('Choose a file and enter its password.');let rd=new FileReader();rd.onload=async()=>{try{await unlock(rd.result,p);await saveDb();hidden($('auth-modal'),true);refresh()}catch(x){alert('Import failed: '+err(x))}};rd.readAsArrayBuffer(f)};
$('btn-open-scanner').onclick=async()=>{if(!db)return hidden($('auth-modal'),false);hidden($('scanner-modal'),false);let v=$('camera-stream'),can=$('capture-canvas');try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});v.srcObject=stream;await v.play();let ctx=can.getContext('2d');timer=setInterval(()=>{if(v.readyState<2||!window.jsQR)return;can.width=v.videoWidth;can.height=v.videoHeight;ctx.drawImage(v,0,0,can.width,can.height);let q=jsQR(ctx.getImageData(0,0,can.width,can.height).data,can.width,can.height);let r=q&&parse(q.data);if(r&&r.ssid){clearInterval(timer);stream.getTracks().forEach(t=>t.stop());hidden($('scanner-modal'),true);openForm(r)}},400)}catch(e){$('scan-status').textContent=err(e)}};$('btn-close-scanner').onclick=()=>{if(timer)clearInterval(timer);if(stream)stream.getTracks().forEach(t=>t.stop());hidden($('scanner-modal'),true)};hidden($('auth-modal'),false);refresh()});
})();
